#Laboratório 4

###Questão 1

Carregue a base iris e a separe em treino e teste usando 40% dos exemplos para teste. Reduza a
base de treino para ter apenas os 24 exemplos iniciais e a de teste para ter apenas os 16 exemplos
iniciais. Considere que o valor 1.5 representa um elemento ausente. Substitua as ocorrências de
valores ausentes pelo valor mais frequente nas bases de treino e de teste reduzidas.

In [8]:
from sklearn import datasets

iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    iris_X,iris_y,test_size=0.4,random_state=0)

X_train = X_train[:24]
y_train = y_train[:24]

X_test = X_test[:16]
y_test = y_test[:16]

#print(X_train)

In [9]:
from sklearn.impute import SimpleImputer

imp_x_train = SimpleImputer(missing_values=1.5, strategy='most_frequent')
#print(X_train)
new_X_train = imp_x_train.fit_transform(X_train)
#print('\n')
#print(new_X_train)

###Questão 2

Utilize agora os mesmos valores mais frequentes usados na base de treino na base de teste do
exercício 1.

In [10]:
#print(X_test)
new_X_test = imp_x_train.transform(X_test)
#print('\n')
#print(new_X_test)

###Questão 3

Padronize a base de treino do exercício 1 e utilize os mesmos fatores de normalização para
padronizar a base de teste.

In [17]:
from sklearn.preprocessing import StandardScaler

#Padronizar - colocar entre 0 e 1
scaler = StandardScaler()
scaler.fit(X_train)
X_train_norm = scaler.transform(X_train)
print(X_train_norm)

X_test_norm = scaler.transform(X_test)

print('\n')
print(X_test_norm)

[[ 0.33603962  0.76296356  0.52477983  0.64940905]
 [-1.15287438  0.08477373 -1.20624749 -1.2988181 ]
 [ 0.08788728 -0.81947938  0.88292342  1.0668863 ]
 [-0.16026505 -0.81947938  0.34570804  0.2319318 ]
 [-0.16026505 -0.36735282 -0.01243554  0.2319318 ]
 [-0.28434121 -1.27160593  0.22632685  0.2319318 ]
 [ 0.46011578 -0.14128955  0.58447043  0.37109089]
 [ 1.82495362  0.310837    1.42013879  0.92772721]
 [-0.53249355  1.44115338 -1.26593808 -1.2988181 ]
 [-1.77325521 -0.14128955 -1.50470047 -1.43797718]
 [ 0.83234428 -0.81947938  1.00230461  1.0668863 ]
 [-0.03618888 -0.14128955  0.34570804  0.09277272]
 [-0.40841738  0.76296356 -1.14655689 -1.2988181 ]
 [-0.03618888  3.02359632 -1.26593808 -1.02049994]
 [ 1.45272512  0.08477373  0.76354222  0.51024997]
 [-1.40102671  0.08477373 -1.26593808 -1.2988181 ]
 [ 0.21196345 -0.14128955  0.88292342  0.92772721]
 [-0.78064588 -1.27160593 -0.37057912 -0.04638636]
 [-1.40102671  0.76296356 -1.32562868 -1.15965902]
 [ 0.58419195 -1.94979576  0.52

###Questão 4

Discretize a base Z_Train usando a estratégia de igual frequência nos intervalos e utilize os
mesmos intervalos para discretizar a base Z_Test. Repita depois usando a estratégia de igual
tamanho dos intervalos. Atenção: crie novas bases para não alterar a definição original de Z_Train e
Z_Test.

In [21]:
#outra técnica - Discretizar - colocar em valores discretos

from sklearn.preprocessing import KBinsDiscretizer

est = KBinsDiscretizer(encode='ordinal')

X_train_disc = est.fit_transform(X_train)

print(X_train_disc)

X_test_disc = est.transform(X_test)

print('\n')
print(X_test_disc)



[[3. 4. 3. 3.]
 [0. 3. 1. 1.]
 [3. 1. 4. 4.]
 [2. 1. 2. 2.]
 [2. 1. 1. 2.]
 [1. 0. 2. 2.]
 [3. 2. 3. 3.]
 [4. 3. 4. 4.]
 [1. 4. 1. 1.]
 [0. 2. 0. 0.]
 [4. 1. 4. 4.]
 [2. 2. 2. 1.]
 [1. 4. 1. 1.]
 [2. 4. 1. 1.]
 [4. 3. 3. 3.]
 [0. 3. 1. 1.]
 [3. 2. 4. 4.]
 [1. 0. 1. 1.]
 [0. 4. 0. 1.]
 [3. 0. 3. 3.]
 [4. 4. 4. 4.]
 [2. 1. 2. 2.]
 [0. 2. 0. 0.]
 [4. 2. 4. 4.]]


[[3. 1. 4. 4.]
 [3. 0. 2. 1.]
 [1. 4. 0. 1.]
 [4. 1. 4. 4.]
 [1. 4. 1. 1.]
 [4. 3. 4. 4.]
 [1. 4. 0. 1.]
 [4. 3. 3. 3.]
 [4. 1. 3. 3.]
 [3. 1. 2. 2.]
 [3. 0. 4. 3.]
 [4. 3. 3. 3.]
 [3. 1. 3. 1.]
 [4. 1. 3. 3.]
 [3. 1. 3. 3.]
 [0. 4. 0. 0.]]


###Questão 5

Leia a base de dados breast cancer e execute 3 rodadas de validação cruzada aninhada
estratificada, porém use padronização em todas as características da base. Use o classificador KNN
com k = {1, 3, 5}. Apresente a acurácia obtida em cada fold de teste, assim como a média da
acurácia, desvio padrão e intervalo de confiança.

In [38]:
from sklearn import datasets
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score,cross_val_predict,cross_validate
from sklearn.neighbors import KNeighborsClassifier
from scipy import stats
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline


cancer = datasets.load_breast_cancer()

scalar = StandardScaler()

kNN = KNeighborsClassifier()

pipeline = Pipeline([('transformer',scalar),('estimator',kNN)])

grade = {'estimator__n_neighbors': [1,3,5]}

gs = GridSearchCV(estimator = pipeline, param_grid = grade,
                  scoring = 'accuracy', cv = 4)

#repetir 3x o procedimento - dividirá os 10 folds de maneira diferente
rkf = RepeatedStratifiedKFold (n_splits = 10, n_repeats=3)

scores = cross_val_score(gs,cancer.data,cancer.target,
                         scoring='accuracy', cv = rkf)

#acurácia obtida em cada fold de teste
print(scores)

mean = scores.mean()
std = scores.std()
inf, sup = stats.norm.interval(0.95, loc=mean, 
                               scale=std/np.sqrt(len(scores)))


print("\nMean Accuracy: %0.2f Standard Deviation: %0.2f" % (mean, std))
print ("Accuracy Confidence Interval (95%%): (%0.2f, %0.2f)\n" % 
       (inf, sup)) 


[1.         0.92982456 0.96491228 0.96491228 1.         0.94736842
 0.9122807  0.94736842 0.96491228 1.         0.98245614 0.94736842
 1.         0.92982456 0.98245614 0.9122807  0.92982456 0.98245614
 0.92982456 0.98214286 1.         0.9122807  0.98245614 1.
 0.9122807  0.96491228 0.96491228 0.98245614 1.         0.98214286]

Mean Accuracy: 0.96 Standard Deviation: 0.03
Accuracy Confidence Interval (95%): (0.95, 0.97)



###Questão 6

Crie um dataset com 5 exemplos com dados nominais para condições do dia com temperatura
(baixa, média e alta), aparência (ensolarado, nublado, chuvoso) e vento (pouco, muito). Transforme
os dados de temperatura e vento para o formato ordinal e o de aparência para o formato binário.


In [62]:
import pandas as pd

data = {
    'temperatura' : ['baixa','alta','média','baixa','média'],
    'aparencia': ['nublado','nublado','chuvoso','chuvoso','ensolarado'],
    'vento': ['muito','pouco','pouco','pouco','muito']
}

df = pd.DataFrame(data)
df


temperatura   aparencia  vento
0       baixa     nublado  muito
1        alta     nublado  pouco
2       média     chuvoso  pouco
3       baixa     chuvoso  pouco
4       média  ensolarado  muito

In [63]:
#temperatura e vento para o formato ordinal

temp_map = {'alta': 2,'média': 1,'baixa': 0}

df['temperatura'] = df['temperatura'].map(temp_map)

vento_map = {'muito': 1,'pouco': 0}

df['vento'] = df['vento'].map(vento_map)

df

temperatura   aparencia  vento
0            0     nublado      1
1            2     nublado      0
2            1     chuvoso      0
3            0     chuvoso      0
4            1  ensolarado      1

In [64]:
from sklearn.preprocessing import OneHotEncoder

df = pd.get_dummies(df[['temperatura', 'aparencia', 'vento']])
df

temperatura  vento  aparencia_chuvoso  aparencia_ensolarado  \
0            0      1                  0                     0   
1            2      0                  0                     0   
2            1      0                  1                     0   
3            0      0                  1                     0   
4            1      1                  0                     1   

   aparencia_nublado  
0                  1  
1                  1  
2                  0  
3                  0  
4                  0

###Questão 7

Compare o desempenho em termos de acurácia do método PCA com três componentes com o
método de seleção univariada de características usando análise de variância e selecionando 3
características no dataset wine. Use o classificador Vizinho Mais Próximo (k = 1) e o método de
divisão percentual com 30% da base usada para teste.

In [65]:
from sklearn.datasets import load_wine

wine = load_wine()

kNN = KNeighborsClassifier(n_neighbors=1)

X_train,X_test,y_train,y_test = train_test_split(
    wine.data,wine.target,test_size=0.3,random_state=0)

In [71]:
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_validate

# condensar a informação contida em várias variáveis originais em um conjunto 
# menor de variáveis estatísticas (componentes) com uma perda mínima de 
# informação.
pca = PCA(n_components=3)
#treinando
pca_tr = pca.fit(X_train)

#reduz a base de treino em 3 colunas 
X_tr = pca_tr.transform(X_train)
X_ts = pca_tr.transform(X_test)

kNN.fit(X_tr,y_train)

print ('accuracy = ', kNN.score(X_ts, y_test))

accuracy =  0.7222222222222222


In [73]:
#método de seleção univariada de características 
#usando análise de variância e selecionando 3 características no dataset wine

from sklearn.feature_selection import SelectKBest

selection = SelectKBest(k=3)
selection.fit(X_train, y_train)

X_tr = selection.transform(X_train)
X_ts = selection.transform(X_test)

kNN.fit(X_tr, y_train)
print ('accuracy = ', kNN.score(X_ts, y_test))



accuracy =  0.6666666666666666


###Questão 8

Obtenha o desempenho (acurácia média, desvio padrão e intervalo de confiança a 95%) do
método de seleção multivariada de características com seleção sequencial para frente e selecionando
3 características no dataset wine. Use padronização, o classificador K Vizinhos Mais Próximo (k =
1, 3 ou 5) e o método de validação cruzada aninhada com 3 repetições de 10 folds.

In [86]:
#Seletor de caracteristicas guloso - SEM PADRONZAÇÃO - KNN 3
from sklearn.feature_selection import SequentialFeatureSelector

fs_forward = SequentialFeatureSelector(kNN, n_features_to_select=3,
                direction='forward')

fs_forward.fit(wine.data, wine.target)

fs_selection = fs_forward.transform(wine.data)

#print(fs_selection)

knn = KNeighborsClassifier(n_neighbors=3)

scores_fs_selection = cross_validate(knn, fs_selection, wine.target,cv=10)

test_scores = scores_fs_selection['test_score']
print(f'Media: {test_scores.mean():.2f} Std: {test_scores.std():.2f}')
intervalConf = stats.norm.interval(0.95, loc=test_scores.mean(), 
                               scale=test_scores.std()/np.sqrt(len(test_scores)))
print("Intervalo de confiança: ",intervalConf)

Media: 0.93 Std: 0.06
Intervalo de confiança:  (0.8956606346437124, 0.9696988424804707)


In [87]:
stanScaler = StandardScaler()

kNN = KNeighborsClassifier()

fs_forward = SequentialFeatureSelector(kNN, n_features_to_select=3, direction='forward')

pipeline = Pipeline([('scaler', stanScaler), ('transformer', fs_forward), ('estimator', kNN)])

grade={'estimator__n_neighbors': [1,3,5]}

rkf = RepeatedStratifiedKFold(n_splits=10, n_repeats=3)

gs = GridSearchCV(estimator=pipeline, param_grid = grade, 
                  scoring='accuracy', cv = 4)

scores = cross_val_score(gs, wine.data,wine.target, scoring='accuracy', cv = rkf)
print(scores)

mean = scores.mean()
std = scores.std()
inf, sup = stats.norm.interval(0.95, loc=mean, 
                               scale=std/np.sqrt(len(scores)))

print("\nMean Accuracy: %0.2f Standard Deviation: %0.2f" % (mean, std))
print ("Accuracy Confidence Interval (95%%): (%0.2f, %0.2f)\n" % 
       (inf, sup)) 

[0.94444444 0.88888889 0.88888889 0.88888889 0.94444444 0.94444444
 0.88888889 0.94444444 0.94117647 0.94117647 0.83333333 0.94444444
 0.94444444 1.         0.94444444 1.         0.94444444 0.94444444
 0.88235294 0.88235294 1.         0.88888889 0.94444444 0.94444444
 0.77777778 0.88888889 0.94444444 1.         0.94117647 0.88235294]

Mean Accuracy: 0.92 Standard Deviation: 0.05
Accuracy Confidence Interval (95%): (0.91, 0.94)

